import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const sha = resolveSha();
const built = new Date().toISOString();
const out = join(dirname(fileURLToPath(import.meta.url)), "../src/version.generated.ts");

const source = `// Generated by scripts/write-version.mjs. Do not edit.
export const VERSION = {
  sha: ${JSON.stringify(sha)},
  built: ${JSON.stringify(built)},
} as const;
`;

writeFileSync(out, source);

function resolveSha() {
  const fromEnv = (process.env.WORKERS_CI_COMMIT_SHA || process.env.GITHUB_SHA || "").trim();
  if (fromEnv) return fromEnv.slice(0, 7);
  try {
    const full = execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
    if (full) return full.slice(0, 7);
  } catch {
    // Fresh checkout without git metadata falls through to "dev".
  }
  return "dev";
}
